#!/usr/bin/env sh

CL='\e[1;33m'
NC='\e[0m'

printf "${CL}----------------------------------------------------------------${NC}\n"
printf "${CL}▶                        RUNNING ESLINT                        ◀${NC}\n"
printf "${CL}----------------------------------------------------------------${NC}\n"

cd frontend
npx lint-staged
